### ISSUE TITLE
MacOS CI test is flaky

### ISSUE THREAD

**Issue by ianbotsf** [awslabs/smithy-kotlin#739]
The `ByteChannelRequestBodyTest.testJobCancelled` test in **:runtime:protocol:http-client-engines:http-client-engine-okhttp:allTests** often fails during CI runs ([example run](https://github.com/awslabs/smithy-kotlin/actions/runs/3481757936/jobs/5823252875)).

The following test failure is seen:

```
ByteChannelRequestBodyTest[jvm] > testJobCancelled()[jvm] FAILED
    kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 1000 ms
        at (Coroutine boundary.()
        at aws.smithy.kotlin.runtime.http.engine.okhttp.ByteChannelRequestBodyTest$testJobCancelled$1$1.invokeSuspend(ByteChannelRequestBodyTest.kt:127)
        at aws.smithy.kotlin.runtime.http.engine.okhttp.ByteChannelRequestBodyTest$testJobCancelled$1.invokeSuspend(ByteChannelRequestBodyTest.kt:123)

        Caused by:
        kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 1000 ms
            at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
            at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
            at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
            at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
            at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
            at java.lang.Thread.run(Thread.java:748)
```

**Comment by ianbotsf** [comment]
Performed several measurements of CI timing across all OSs and found:

|             | **Linux** | **MacOS** | **Windows** |
|-------------|----------:|----------:|------------:|
| **Mean**    | 730       | 1091      | 582         |
| **Std Dev** | 82        | 360       | 156         |
| **Median**  | 717       | 945       | 500         |

(All timings in milliseconds)

It seems the runners for MacOS are simply slower than for the other OSes.

**Comment by ianbotsf** [comment]
Updated CI test timeout.
